### ISSUE TITLE
Can you please let us know how to add the content preview for this?

### ISSUE THREAD

**Issue by gbalakrishnan-cx** [pauloamgomes/CockpitCMS-React-Static#18]
Your contribution on this very nice. I would like to know how to add the content preview on the same project.

**Comment by pauloamgomes** [comment]
Hi @gbalakrishnan-cx , the content preview needs to be implemented on your FE, for example, let's assume you have a React application that has a dynamic route for the preview. 
The component that handles that route will receive an event message from Cockpit with the entry payload, and your component will require to render that data.

That is exemplified on the file: https://github.com/pauloamgomes/CockpitCMS-React-Static/blob/master/react-app/src/pages/Preview.js

Keep also in mind that you need to configure in Cockpit your collection type to use the preview url the same url of your FE application is running.
