### ISSUE TITLE
Unable to start server on Linux 18.4 LTS in CockpitCMS-React-Static/react-app example

### ISSUE THREAD

**Issue by namwanza** [pauloamgomes/CockpitCMS-React-Static#2]
Hello,

Can someone help me and tell me why i can’t start local server when i run yarn install.

When i run yarn start, am getting an error here .

namwanza@Ronnie:/mnt/c/CockpitCMS-React-Static/react-app$ **yarn start**
**yarn run v1.12.3
$ sh -ac '. .env.local; react-static start’
sh: 1: .: .env.local: not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

Here is my###  package.json

{
“name”: “react-static-cockpit-example”,
“version”: “1.0.1”,
“main”: “index.js”,
“license”: “MIT”,
“scripts”: {
“start”: “sh -ac ‘. .env.local; react-static start’”,
“stage”: “react-static build --staging”,
“build.dev”: “sh -ac ‘. .env.development; react-static build’”,
“build.prod”: “sh -ac ‘. .env.production; react-static build’”,
“bundle”: “react-static bundle”,
“export”: “react-static export”,
“serve”: “serve dist -p 3000”,
“deploy.dev”: “yarn build.dev && rm -rf …/public/html/* && cp -rf dist/* …/public/html/”,
“deploy.prod”: “yarn build.prod && rm -rf …/docs/* && cp -rf dist/* …/docs/”
},
“dependencies”: {
“axios”: “^0.18.0”,
“bootstrap”: “^4.1.3”,
“formik”: “^1.3.1”,
“graphql-request”: “^1.8.2”,
“htmr”: “^0.7.0”,
“leaflet”: “^1.3.4”,
“react”: “^16.0.0”,
“react-dom”: “^16.0.0”,
“react-highlight.js”: “^1.0.7”,
“react-hot-loader”: “^4.0.0-beta.21”,
“react-leaflet”: “^2.1.0”,
“react-player”: “^1.6.6”,
“react-router”: “^4.2.0”,
“react-static”: “^5.9.12”,
“reactstrap”: “^6.5.0”,
“styled-components”: “^3.4.10”
},
“devDependencies”: {
“eslint-config-react-tools”: “1.x.x”,
“serve”: “>=7.0.0”
}
}

Thanks

**Comment by pauloamgomes** [comment]
@Namwanza can you confirm you have a .env.local file on the directory? You should because file is commited.

**Comment by pauloamgomes** [comment]
Also check if it runs with npm, try ```npm run start```

**Comment by namwanza** [comment]
> @Namwanza can you confirm you have a .env.local file on the directory? You should because file is commited.
 
![image](https://user-images.githubusercontent.com/32957478/48614338-0a7f8000-e99f-11e8-9eb3-739d97b29dee.png)

**Comment by namwanza** [comment]
I still get an error when i run npm run start.
Here. 
![image](https://user-images.githubusercontent.com/32957478/48614492-6f3ada80-e99f-11e8-9796-1e37ad3e6794.png)

**Comment by pauloamgomes** [comment]
Humm, you are on windows with WSL, tbh never tried to run node, npm/yarn stuff there! You may need to investigate further about the issue, is not related to the project but more on how npm/yarn shall be installed on WSL.

**Comment by colinappnovation** [comment]
@Namwanza this https://github.com/Microsoft/WSL/issues/1896 could be related to your current error which I noticed in your Ubuntu console output.
